from flask import Flask, render_template
import random

app = Flask(__name__)

wulgaryzmy = [
    "Znowu ci handlowcy coś namieszali!",
    "Jak mam to zaplanować, skoro brief wygląda jakby pisał go pies?",
    "Czy oni serio myślą, że czas się rozciąga?",
    "Jakbym miał drukarkę czasu, to bym może zdążył.",
    "Niech mi ktoś powie, jak to ma zejść z maszyny w 2 godziny.",
    "Kto im powiedział, że kolory same się dopasują?",
    "Ciekawe czy handlowiec w ogóle widział tę maszynę na oczy.",
    "Dajcie mi dzień bez cudów i magii w plikach.",
    "Znów chcą zadruk na złotym podłożu bez dodatkowych kosztów.",
    "Niech ktoś im powie, że lakier to nie Photoshop.",
    "Jak mam zaplanować coś, czego fizycznie nie da się wydrukować?",
    "Brief ma 3 linijki, a oczekują cuda na kiju.",
    "Handlowcy myślą, że czas produkcji to fikcja literacka.",
    "Siedzę tu znowu i ratuję projekt zrobiony w Paintcie.",
    "Ciekawe kiedy handlowcy odkryją istnienie specyfikacji technicznych.",
    "Ile razy mam mówić, że nie robimy cudów bez materiałów?",
    "Znowu plik bez spadów. Ciekawe jak im to wychodzi.",
    "Ktoś chyba myśli, że pantone to styl życia, nie kolor.",
    "Dzięki handlowcom znowu siedzę po godzinach.",
    "Planista to nie wróżbita, ale coraz częściej się nim czuję."
    "A to, że coś się da wydrukować w Corelu, nie znaczy, że da się to zrobić w rzeczywistości, geniuszu.",
    "Kiedy ty składasz ofertę, ja już wiem, że dziś nie wyjdę przed północą.",
    "Podobno miałeś mówić klientom prawdę. A nie bajki z mchu i szarej folii.",
    "Czy ty potrafisz chociaż raz sprzedać coś, co istnieje w realnym świecie?",
    "Klient chciał na wczoraj? Powiedz mu, że ty też chciałeś mózgu przy narodzinach.",
    "Znowu zrobiliście promocję bez pytania planisty? A co, fabryka miała nudny tydzień?",
    "Handlowiec to taki Pokémon – dużo szumu, zero ataku.",
    "Wy naprawdę sądzicie, że czas druku to magiczne 15 minut między kawą a siku?",
    "Drukarnia to nie drukarka w biurze, dzbanie.",
    "Masz pojęcie, ile trwa przezbrojenie? Nie? To zamknij Excela i przestań pierdolić.",
    "Zróbmy to na jutro? Zajebiście. To jeszcze mi przynieś elfów do pomocy.",
    "Dajcie mi miesiąc bez twojego projektu, to może serce przestanie mnie boleć.",
    "Nie, nie da się dodać ‘jeszcze jednego SKU’. To nie jest pierdolony Word.",
    "Wasz ‘krótki nakład’ to mój wielki rozpierdol.",
    "Nie wiem, co gorsze – twoje plany czy twoje pomysły.",
    "Kiedy handlowiec mówi ‘mały projekt’, wiem, że będzie przypominał Tolkiena.",
    "‘Tylko zmiana koloru’ – powiedział i wysłał nowy plik, nowy termin, nowe życie.",
    "Zrobimy to na nocce? Oczywiście, drukarnia to przecież całodobowe spa.",
    "Klient nie zaakceptował? To chyba pierwszy, który ma rozum.",
    "Gdybyś miał pojęcie o technologii, nie byłbyś handlowcem, tylko człowiekiem.",
    "Masz więcej obietnic niż polityk przed wyborami. A ja mam więcej nerwów niż toneru.",
    "Jakbyście przestali wciskać klientom 7 cud świata, może byśmy zrobili coś na czas.",
    "Zamiast kawy, dajcie mi listę waszych obietnic – bardziej mnie pobudzi.",
    "Klient zmienił zdanie? A co mnie to kurwa obchodzi?",
    "Masz tyle pojęcia o druku, co papuga o lotnictwie.",
    "Nie mogę zrobić cudów, ale mogę ci pokazać, gdzie wsadzić swoje Zlecenie.",
    "Niech klient sobie wydrukuje na drukarce domowej, skoro ‘to tylko etykieta’.",
    "Jakbyście mieli mózgi, to byście nie przynosili Pilnych Zamówień po 15:00.",
    "Czy ten termin to twój żart, czy diagnoza psychiatryczna?",
    "Masz pomysł na nową usługę? Zajebiście. Ale może najpierw dokończ stary burdel.",
    "Znowu sprzedałeś coś, co nie istnieje? Brawo, Harry Potterze handlu.",
    "Tak, klient chciał na jutro. A ja chcę wódkę i urlop.",
    "Dobrze, że mówisz o terminie. Bo logika to nie twoja mocna strona.",
    "Przestań pierdolić o ‘szybkim druku’. To nie ksero w Żabce.",
    "Twój klient nie jest wymagający. Jest jebnięty.",
    "W Excelu wszystko się zgadza, tylko że życie to nie kolumna B.",
    "Ile razy mam powtarzać: próbki robi się PRZED, nie PO terminie!",
    "Gdybyś czytał specyfikacje, nie musiałbyś mnie pytać o wszystko jak przedszkolak.",
    "W twojej głowie drukarnia to magiczna kraina, gdzie wszystko się robi samo.",
    "Skoro twój klient wie lepiej, to niech sam sobie to wydrukuje w piwnicy.",
    "Handlowiec to taki byt, co zniknie po sprzedaży, a wróci, jak klient zacznie krzyczeć.",
    "Twoje ‘urgent’ znaczy tylko jedno – spierdoliliście coś znowu.",
    "Zawsze, gdy mówisz ‘mała zmiana’, umiera jedna maszyna.",
    "Czy jest coś, czego jeszcze dziś nie spierdoliliście?",
    "Wasze założenia są jak bajki – ładne, ale nierealne.",
    "Zamiast mówić ‘na już’, spróbuj raz powiedzieć ‘na zatydzień’.",
    "Dzięki tobie znam każdą wersję ‘niestandardowego zamówienia’.",
    "Nie wiem, co gorsze – plik z agencji, czy twoje zlecenie bez danych.",
    "Jakbyś jeszcze raz powiedział ‘to proste’, to ci przypnę Zamówienie do czoła.",
    "Powiedziałeś klientowi, że ‘damy radę’? Super. Teraz weź mu to wydrukuj tyłkiem.",
    "Twoje ‘tylko 5 tys. sztuk’ to mój ósmy krąg planistycznego piekła.",
    "Jak chcesz jutro gotowe, to może powiedz mi to wczoraj.",
    "Wiesz co jest szybsze niż twoje terminy? Rozwój raka.",
    "Gdyby drukarnia działała tak jak twoje obietnice, bylibyśmy NASA.",
    "Ty sprzedałeś? Gratulacje. Ja teraz muszę to wyprodukować, kurwa jego mać.",
    "Nie mogę przewidzieć awarii maszyny. Tak samo jak twojego idiotyzmu.",
    "Zamówienia last minute to wasz fetysz, czy zwykła niekompetencja?",
    "Jak twoje pliki są tak dobre jak twoje terminy, to wolę umrzeć teraz.",
"Nie da się zrobić w 2 dni czegoś, co wymaga tygodnia. To nie są jebane czary.",
"Kiedy ty dzwonisz z pytaniem o status, ja już wiem, że coś zjebałeś.",
"Twój klient zmienia specyfikację częściej niż ty bieliznę.",
"Tak, ‘standardowy termin’ to nie znaczy ‘na jutro po południu’.",
"Masz tyle pojęcia o produkcji, co koń o fotoskładzie.",
"Twoje zlecenia mają mniej sensu niż instrukcja z IKEA po chińsku.",
"Masz ładny garnitur, szkoda że nic w nim nie działa.",
"W twojej wersji rzeczywistości wszystko działa. W mojej drukarni – nic.",
"Przestań mówić ‘klient nalega’. Klient to nie bóg, a ty nie jesteś jego prorokiem.",
"Jeśli plan był ci potrzebny na dziś rano, to czemu mail przyszedł o 13:45?",
"Ty sprzedajesz marzenia, a ja tonę w koszmarze.",
"Fajnie, że chcesz zrobić klientowi dobrze. Ale czemu ja mam być tym, co musi się schylać?",
"Nie każda maszyna działa na magię. Nawet jeśli wierzysz w jednorożce.",
"Jak jeszcze raz powiesz ‘drukarnia to niech się dostosuje’, to dostosuję ci but do ryja.",
"Dziękuję za kolejny projekt bez danych. Uwielbiam rysować specyfikację na ścianie krwią.",
"Klient nie chce zapłacić za próbki? A ja nie chcę cię więcej widzieć.",
"Zróbmy ‘jakiś proof’. Jakiś proof? Ty masz jakiś mózg?",
"Masz coś wspólnego z etykietą – jesteś do przyklejenia i do wyjebania.",
"Twoje zlecenie wygląda jakbyś je pisał stopą po pijaku.",
"Masz nowy pomysł na cross-selling? Świetnie. Spróbuj najpierw nie spierdolić bazowego zlecenia.",
"Znowu ktoś zapomniał o terminach? To pewnie ty, Sherlocku od klienta.",
"Nie, nie zrobię 5 wersji kolorystycznych na próbę. To nie jest jebana paleta Pantone.",
"Masz mniej kontaktu z rzeczywistością niż brief klienta z branży kosmetycznej.",
"Jak chcesz szybciej, to cofnij się w czasie. Innej opcji nie ma.",
"Nie wiem, czy ty bardziej nie umiesz liczyć dni, czy godzin pracy maszyny.",
"Drukarnia to nie cyrk. Chociaż jak patrzę na wasze Zamówienia, to mam wątpliwości.",
"Wyślij jeszcze raz maila z dopiskiem ‘URGENT’. Może tym razem spłonę z zajebistości.",
"Kiedy słyszę ‘nie chcę nikogo poganiać, ale…’, to już szukam noża.",
"Zastanów się czasem nad tym, co robisz. Chociaż przez pięć sekund.",
"Nie rozumiem, jak ktoś może tyle mówić, a tak mało wiedzieć.",
"To nie są zmiany ‘na chwilę’. To jest zmiana życia i mojej psychiki.",
"Przestań mówić ‘klient chce taniej’. Ja chcę spokojnie umrzeć. Też się nie da.",
"Jeśli znowu zapytasz, czy coś już gotowe, to ja zapytam, czy ty w ogóle tu pracujesz.",
"Nie wiem co boli bardziej – ten nakład, czy twoja obecność.",
"Klient zmienił format? To może niech zmieni też drukarnię, co?",
"Twój Excel to największe kłamstwo po Biblii.",
"Sprzedajesz jakbyś miał udar. Szkoda, że nikt nie wezwał lekarza.",
"Gdyby głupota miała logo, to miałbyś je na wizytówce.",
"Nie jestem czarodziejem. Jestem planistą. Chociaż przez ciebie jedno i drugie znaczy to samo.",
"Twoje ‘to tylko drobna zmiana’ powoduje u mnie mikrourazy psychiczne.",
"Nie, nie zrobię tego w weekend. Nawet Jezus odpoczywał w niedzielę.",
"Jak znowu powiesz ‘przesuń coś’, to przesunę ci mózg na margines.",
"Twoje zlecenie jest jak sraczka – pojawia się nagle i jebie cały dzień.",
"Nie da się zrobić szybciej. Chyba że zrezygnujesz z jakości, koloru i rozumu.",
"Ciebie chyba ktoś z działu bajek zatrudnił.",
"Nie potrzebuję kolejnego ‘tematu na szybko’. Potrzebuję psychologa.",
"Masz mniej sensu niż CMYK w projekcie RGB.",
"Zróbmy coś inaczej? Super. A może zróbmy coś raz porządnie?",
"Klient chce termin na wczoraj? Zajebiście. Ja chcę wakacje w Japonii.",
"Twoje zlecenia przypominają mi jedzenie z mikrofalówki – szybko, tanio i gówno.",
"Każde twoje ‘musi być dziś’ skraca mi życie o godzinę.",
"Przy tobie ‘deadline’ to nie termin. To przekleństwo.",
"Zamawianie u ciebie to jak rosyjska ruletka, ale z więcej niż jedną kulą.",
"Jeśli ten klient to VIP, to ja jestem królową Anglii i też mam dosyć.",
"Tak, mogę to zaplanować. Ale najpierw wyślę cię do diabła.",
"Twoje ‘tylko przesuń to o dzień’ to moja nerwica lękowa.",
"Czasami marzę, że twoje maile wpadają do spamu na zawsze.",
"Nie, nie możemy dodać jeszcze jednej wersji. Możemy za to usunąć ciebie z listy kontaktów.",
"Twoje zlecenia są jak horror – nigdy nie wiadomo, co wyskoczy.",
"To nie jest plan produkcyjny. To jest jebana bitwa o przetrwanie.",
"Twój klient to artysta? Świetnie. Ja nie jestem jego jebaną muzą.",
"Zrobimy to jutro... jeśli przeżyję dzisiaj.",
"Twoje pytania to mój system ostrzegania przed zawałem.",
"Kiedy słyszę ‘jest szansa że...’, wiem że będzie katastrofa.",
"Masz jakieś hobby poza psuciem mi dnia?",
"Twoje Zamówienie wygląda jak lista zakupów dziecka z ADHD.",
"To nie ja jestem trudny. To twoje zlecenia są z piekła rodem.",
"Mówisz, że ‘wszystko ogarnięte’? Kłamiesz jak z nut, Mendelssohnie sprzedaży.",
"Przez ciebie już nawet ksero się na mnie obraziło.",
"Przestań mówić ‘będzie pan zadowolony’. Bo pan planista już nie żyje.",
"Masz dar do wyciągania z ludzi tego, co najgorsze. Gratulacje, czarodziejko chaosu.",
"Zastanawiam się, czy ty w ogóle umiesz czytać specyfikacje, czy tylko udajesz.",
"Każde ‘to jeszcze tylko jedna rzecz’ brzmi jak wyrok.",
"W twoim świecie wszystko się da. W moim – nic się nie zgadza.",
"Zróbmy tak: ty przestaniesz myśleć, ja przestanę krzyczeć.",
"Jak znowu usłyszę ‘ale klient nie wiedział’, to wyrwę sobie uszy.",
"To ty powiedziałeś klientowi, że możliwe? To teraz mu to kurwa wytłumacz.",
"Twoje ‘usprawnienia’ to dla mnie jak kamień do nogi.",
"Masz styl pracy jak Windows 95 – zawieszasz się, kiedy tylko cię potrzebuję.",
"Nie wiem, co boli bardziej – twoja ignorancja czy moja bezsilność.",
"W twojej głowie to może i się spina. Ale tu jest rzeczywistość, geniuszu.",
"To nie jest ‘mały nakład’. To jest wielki ból dupy.",
"Znowu klient zapomniał? Może ma demencję jak ty.",
"Kiedy piszesz ‘szybka akcja’, ja wpisuję cię na czarną listę.",
"Nie wiem, co gorsze – twoje obietnice czy klient, który w nie wierzy.",
"Jeśli ten projekt jeszcze raz wróci do poprawek, złożę wypowiedzenie na papierze termokurczliwym.",
"Ciebie się powinno pakować w folię z ostrzeżeniem: może wywoływać frustrację.",
"Jesteś jak paproch w oku – niby mały, a doprowadza mnie do szału.",
"Twoje ‘po prostu zróbmy’ brzmi jak ‘po prostu się zesrajmy na plan’.",
"Ooo, znowu zlecenie last minute? Nie musisz dziękować, właśnie planowałem sobie spokojne życie.",
"Dzięki za brief napisany czcionką niewidzialności – naprawdę, podziwiam twoje zaangażowanie.",
"Zawsze marzyłem o pracy, w której codziennie dowiaduję się, że znowu muszę robić cud.",
"Nie, nie mamy maszyny do teleportacji. Ale świetnie, że nadal w to wierzysz.",
"To niesamowite, jak bardzo nie masz pojęcia, co robisz, a mimo to ci płacą.",
"Kiedy mówisz ‘klient nie przewidział’, ja też nie przewidziałem, że zostanę zakładnikiem twoich błędów.",
"Czy to Zamówienie było pisane na kolanie, czy po prostu było efektem zamkniętych oczu i otwartego wina?",
"Wspaniale, że klient chce 'luksus', ale budżet ma na ‘bieda z nędzą’.",
"Kiedy ty obiecujesz termin, ja od razu wpisuję ‘piekło’ w kalendarz.",
"Jeśli twoje pomysły byłyby banknotami, to właśnie zapłaciłeś mi w Monopoly.",
"Super, że klient chce siedem wersji. Ja też chcę osiem godzin snu, ale cóż – życie.",
"Dzięki za 'małą korektę'. Przez ciebie znowu odwołałem egzorcyzm u DTP.",
"Kiedy mówisz ‘to pilne’, moje serce bije jak ploter z zatkanym tuszem.",
"Twój zmysł planowania mógłby konkurować z ruchem drogowym w Bombaju.",
"Uwielbiam, kiedy wracasz z poprawkami, których nie zrozumiał nawet autor projektu.",
"Czy naprawdę uważasz, że ‘weź to jakoś zrób’ to pełnoprawna instrukcja?",
"Następnym razem jak klient powie ‘tanio, szybko i dobrze’, każ mu wybrać jedno. Albo zmień klienta.",
"Twoje terminy są jak duchy – wszyscy o nich mówią, nikt ich nie widział.",
"Świetnie, że klientowi się 'odwidziało'. Mnie się też odwidziało być miłym.",
"Tak, jasne, że zmieścimy to wszystko. Jeśli fabryka czasu ruszy produkcję.",
"Twoje zlecenia przypominają origami – z papieru i do wyrzucenia po sekundzie.",
"Kiedy ty mówisz ‘będzie lekko opóźnione’, ja szykuję przemówienie pożegnalne dla maszyny.",
"Twoje projekty mają tyle sensu co trzeci język na etykiecie z miejscem na dwa.",
"Jasne, klient chce efekt WOW. Szkoda, że budżet to efekt ECH.",
"To naprawdę urocze, że wierzysz, że ‘przesuń to o jeden dzień’ to coś bez konsekwencji.",
"Twoja zdolność komplikowania prostych rzeczy to prawdziwe arcydzieło biurowej patologii.",
"Masz takie pojęcie o produkcji jak drukarka o uczuciach – zerowe, ale bardzo głośne.",
"Kiedy zlecasz coś ‘na wczoraj’, pamiętaj, że nie jestem wehikułem czasu. Jeszcze.",
"Czasem się zastanawiam, czy ty naprawdę pracujesz tu, czy po prostu symulujesz chaos.",
"Dziękuję za nowe zlecenie. Byłem właśnie w trakcie oddechu, ale trudno.",
"Jesteś jak Windows Update – pojawiasz się zawsze, gdy wszystko działa dobrze.",
"Twoje pliki to poezja... napisana przez pijanego informatyka.",
"Masz szczęście, że moje przekleństwa nie są fakturowane.",
"Twoje ‘musimy to wydrukować’ brzmi jak zaklęcie z czarnej magii.",
"Chcesz, żeby wszystko było idealnie? A może jeszcze maszynista z koroną?",
"Poważnie, jeszcze jeden deadline i zacznę się modlić do pantonów.",
"Twoja empatia do produkcji ma objętość pliku JPG w 72 dpi.",
"Następnym razem wyślij Zamówienie w dymie z ogniska – przynajmniej będzie klimat.",
"Jestem planistą, nie cudotwórcą. Chociaż ostatnio trudno to rozróżnić.",
"To nie są zmiany. To próba zabójstwa z premedytacją.",
"Mówisz ‘spokojnie, klient dał zielone światło’? Świetnie, bo ja mam czerwone oczy.",
"Dzięki, że wprowadzasz do mojego życia element nieprzewidywalności. Jak choroba weneryczna.",
"Twoje pomysły są jak przeterminowany lakier – nie trzymają się niczego.",
"Nie jestem alfą i omegą, ale przy tobie czuję się jak cała alfabetowa burza.",
"Twoje decyzje mają mniej sensu niż złoty nadruk na bibułce.",
"Czasami myślę, że twój komputer ma tylko przycisk ‘Wyślij problem do planisty’.",
"Mam dla ciebie niespodziankę: też nie lubię ciebie.",
"Twoja komunikacja ma styl gołębia – dużo gówna, zero treści.",
"Nie wiem co boli bardziej – ten projekt, czy fakt, że nadal się widujemy codziennie.",

]

@app.route("/")
def index():
    tekst = random.choice(wulgaryzmy)
    return render_template("index.html", tekst=tekst)
